filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/sample/*.log

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

# output.elasticsearch:
#   hosts: ["http://elasticsearch:9200"]
#   username: "elastic"
#   password: "changeme"
setup.kibana:
  host: "http://kibana:5601"

monitoring.enabled: false